services:
  spark-dev-environment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-dev-environment
    hostname: spark-dev-environment
    volumes:
      - ../:/workspaces
      - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa
      - $HOME/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - $HOME/.ssh/known_hosts:/root/.ssh/known_hosts
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    entrypoint: sleep infinity
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: 96g