- name: Deploy Spark container to contabo
  hosts: contabo_dev
  remote_user: dev
  tasks:
  - name: Pull git repo
    ansible.builtin.git:
      repo: git@github.com:Rusha-Corp/rusha_spark_dev_env.git
      dest: spark-dev-env
      version: main
      force: yes

  - name: run docker-compose up
    shell: |
      docker-compose up --build -d
    args:
      chdir: spark-dev-env